language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-apayol
  api_key:
    secure: Z6j/PxkT2gvoAGHen9c3kMNPRLnmMTvyOSgaSbU74vzzxaYvDgTf6K1NL8Oe4RvBv5iUPXS+riKuR5dYtW7mCLuqSffs7Y43khs2MCcvLn3KR958rQWizPPvfmpD35sVCqCMbOmMlRFrFkKdfxqMupniwtrj/PIqt3F8quU1LlAXRL7qWEaLgUbsQCQD+6YfiYI2KmVOR6gRytEkUSIpHSjhmt1YCd9dZ3COKJGN/gzOMVKiubZ+LoEilhejX5rK5o5xhKiKXqPkZ209QVyyfJ2jg8JpkhmmsSwMRf0ebVHBPiZl1pZkxpi+cgH9DADNSzajgY/eFdDuM+TyTXCMUmPYUAyxMs9m1ihboNCSt1EKm5uyzx/Oa1eCbI4uAdDIhlB1AjGvvvy0fgBD9FKKTnbNAqoBbx/r8xpjWBlqXljKar+Sfq4cymzl4T/hTVZ8L3jKLfoYy1oKkhHPrNUkEe9y41vLRjq1SYaJvEhQROfSO+cwH98vhlrnGgU/1z/Pkb9WD1laH3Di+NA6jbW6BAhwTfRtVge4KSR2PKmKseECz5xX1v2ehtx70LPwvvzhpKSMdXrdQ6qhVOZuf+4b/Sz6kTZrYrGceDLsaWJWo3znioxAMOVIjphvfEDTTzEvLaPZFiTOO8JSV2l6FuNMD4R0rSoi0Tjm2IoZds8YY1w=
